### ISSUE TITLE
"Which Roles Can See This Link" behaves like RadioButton and not checklist

### ISSUE THREAD

**Issue by larrygauthier** [JunglePlugins/User-Menus#8] opened 2019-07-01 15:48 UTC
After declaring that "Logged in Users" can see a link, the drop-down displays checkboxes for Administrator, Editor, Author, Contributor and Subscriber. If I select more than one of those boxes, only users assigned to the first group can see the menu choice.

For example, if I select three choices, Administrators, Editors and Authors, then only Administrators (not Editors or Authors) see the menu choice. If I un-select Administrators and leave Editors and Authors selected, then only Editors (not Authors) see the menu choice.

Thanks in advance for looking at this,

Larry

**Comment by danieliser** [comment] 2019-07-03 18:32
@larrygauthier - Sounds like a conflict somewhere. The code isn't written that way:

https://github.com/JunglePlugins/User-Menus/blob/master/includes/classes/site/menus.php#L53-L65

It simply checks all chosen roles and stops as soon as it detects one that matches.

**Comment by danieliser** [comment] 2019-09-28 21:29
Duplicate of #10. Moving all conversations there as it is the most complete thus far.

**Closed by danieliser** 2019-09-28 21:29 UTC
